header:
  - "# Jon Smith"
  - "## JonSmith@example.com"
  - "## github.com/octocat, jsmith.example.com"

resume:
  projects:
    - "---"
    - "Rattlusume.md"
  experience:
    - "---"
    - "foo.md"
